// Fill out your copyright notice in the Description page of Project Settings.


#include "FirstSCChart.h"



// Sets default values
AFirstSCChart::AFirstSCChart()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

}

// Called when the game starts or when spawned
void AFirstSCChart::BeginPlay() {
	// generated by UE for inheritance
	Super::BeginPlay(); 
	// The SCCharts FSM needs to be ressetted before it can receive the first tick
	SCChartsFSM.Reset();
}

// Called every frame
void AFirstSCChart::Tick(float DeltaTime){
	Super::Tick(DeltaTime); // generated by UE for inheritance
	SCChartsFSM.Tick();
	// this prints a yellow Warning with the text inside Text(..) and our stateID from the
	// SCCharts which is located under tickdata as are any other input or output
	// variable
	UE_LOG(LogTemp, Warning, TEXT("SCChart output: %s"),  *FString(SCChartsFSM.tickData.text));
}

